channels:
    - conda-forge
    - defaults
name:
    stardist-gpu
dependencies:
    - imageio
    - h5py
    - napari
    - python 3.7
    - pip
    - scikit-image
    - tqdm
    - tensorflow-gpu 1.14
    - pip:
        - stardist
